### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by MartinsOnuoha** [nebed/onlinestorecompare#4]
Server throws error on request:
```
File "/home/kratos/Projects/OpenSourcerer/onlinestorecompare/store_functions.py", line 81, in parse_image_slot
    images[:] = [image.a.img.get('data-original') for image in images]
AttributeError: 'NoneType' object has no attribute 'get'
```

`images[:] = [image.a.img.get('data-original') for image in images]` line 81 in `store_functions.py`
Seems to be calling the get method on an undefined object

**Comment by nebed** [comment]
Can you give me a little insight on your setup, I'll try to reproduce and fix the issue

**Comment by nebed** [comment]
But what the error means is the current soup object doesn't have those elements within it, the <a> and the <img>

**Comment by nebed** [comment]
Do you get that error when you request from the API?

**Comment by nebed** [comment]
It still works on my end, pull the most recent changes, as I've made some changes since then.
